### ISSUE TITLE
Error using Eviction_strategy_evaluator

### ISSUE THREAD

**Issue by pg2527** [IAIK/armageddon#2]
Import error : No module named "libflush_eviction_evaluator"

My path to libflush source directory is :
/armageddon-master/libflush/

**Comment by psyte** [comment]
Funny, I had the same problem a few minutes ago.
Fixed it by changing main.py:

```
from libflush_eviction_evaluator.config import parse_device_configuration
from libflush_eviction_evaluator.config import parse_configuration
```
to
```
from eviction_strategy_evaluator.config import parse_device_configuration
from eviction_strategy_evaluator.config import parse_configuration
```
They probably renamed the package recently...

**Comment by pg2527** [comment]
Thanks! It worked for me too.

**Comment by mlq** [comment]
Thank you for spotting this, happened during the clean-up of the code. I've already pushed the change to the repository.
